---
development:
  cloud_name: dwtaw2aai
  api_key: '444617863343465'
  api_secret: q_vbmgEoRol7dCPi1pG7LlwEvXw
  enhance_image_tag: true
  static_image_support: true
production:
  cloud_name: dwtaw2aai
  api_key: '444617863343465'
  api_secret: q_vbmgEoRol7dCPi1pG7LlwEvXw
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dwtaw2aai
  api_key: '444617863343465'
  api_secret: q_vbmgEoRol7dCPi1pG7LlwEvXw
  enhance_image_tag: true
  static_image_support: true
